### ISSUE TITLE
Connection problem

### ISSUE THREAD

**Issue by madsenfr** [KamKam0/ecoledirecte#1]
Hello,

When I try sample code to connect with my own ID and password (verified because it works with postman) I get an error when using https://npm.runkit.com/ to execute the code.

```
const EcoleDirecte = require("@kamkam1_0/ecoledirecte.js")
const Account =  new EcoleDirecte.Account("LOGIN ID", "LOGIN PASSWORD")
let Session = await Account.Login()

```
gives me the folowwing error at new Account in ecoledirecte.js/dist/accounts/Account.js — line 20
```
        this.__session = session;
        // Necessary checks
        if (!session.loginRes || (0, v3_1.isFailure)(session.loginRes))
►     ► throw new Error("Account class must have valid connection");
        const mainAccount = (0, util_1.getMainAccount)(session.loginRes.data.accounts);
        if (!session.token)
            throw new Error("Account class MUST have token");

```

**Comment by KamKam0** [comment]
Bonjour @madsenfr,

Je me permets de te répondre en français compte tenu des infos indiquées sur ton profil 🙂.

Concernant l'erreur que tu rencontres, j'ai du mal à comprendre quel est le rapport direct avec mon module pour être honnête.
 En effet, lorsque je regarde le code de celui-ci (que j'ai fait depuis longtemps, je l'avoue) aucune erreur que tu remontes plus haut n'est présente dans mon code. Par exemple, en aucun cas mon module renvoie l'erreur "Account class must have valid connection" n'est renvoyée.

Concernant les tests, j'ai fait un test de connexion avec des identifiants valides et le code est toujours fonctionnel.

Quant tu auras le temps, serait-il possible d'apporter des précisions à ton souci ?

**Comment by madsenfr** [comment]
Bonjour,
Merci de prendre le temps de répondre.
Je copie simplement le code en exemple dans un moteur node en ligne https://npm.runkit.com et j'obtiens cette erreur.

**Comment by KamKam0** [comment]
Aucun soucis !
En tout cas, merci pour la précision, elle m'a permis de mieux comprendre ton erreur.

En fait, j'ai simplement fait une faute de frappe dans le readme, au lieu de mettre 
" const EcoleDirecte = require("@kamkam1_0/ecoledirecte") "
 j'ai mis 
" const EcoleDirecte = require("@kamkam1_0/ecoledirecte.js") " (il y a un .js en trop).

Si tu remplaces donc @kamkam1_0/ecoledirecte.js par @kamkam1_0/ecoledirecte dans le require, tu devrais t'en sortir.

De mon côté, je vais sortir une nouvelle version la semaine prochaine avec un code revisité et optimisé, la doc sera mise à jour au passage 👍🏻

Merci pour cette remontée !

**Comment by madsenfr** [comment]
Maintenant j'obtiens bien une réponse en mettant le code corrigé sans ".js" dans https://npm.runkit.com, mais c'est une erreur : 

Error {Code: 505, Token: null, Message: "Mot de passe invalide !"}

Pourtant mon mot de passe est bien correct.

**Comment by KamKam0** [comment]
Concernant ce souci, l'erreur ne vient plus du module, car il utilise directement le système d'école directe. Cela veut dire que ton identifiant ou mot de passe est invalide d'après **leur** système 😅.

Comme je l'avais indiqué plus haut, mes tests se sont bien déroulés et le module a bien fonctionné.

**Comment by madsenfr** [comment]
Aurais tu une idée de ce qui peut faire que le code ne passe pas dans https://npm.runkit.com/ ?
J'ai exactement les mêmes headers que dans Postman, mais on dirait que le mot de passe n'est pas correctement interprété.

Pour info, j'ai une skill Alexa qui me donne l'emploi du temps et les notes, mais depuis la fin d'année scolaire de l'année dernière j'ai le même problème avec l'erreur mot de passe invalide et il s'agit aussi d'un NodeJS dans le cloud Amazon.
Par contre, si je mets le token en dur, les autres appels pour récupérer l'emploi du temps ou les notes fonctionnent bien sur Runkit et Alexa.

Je n'ai un problème que pour envoyer ce foutu mot de passe !
